'use client';
import { useState, useEffect, useRef } from 'react';
import { api } from '@/lib/api';
import Link from 'next/link';
import {
  Video,
  Loader2,
  Download,
  RefreshCw,
  ChevronLeft,
  Clock,
  Monitor,
  Smartphone,
  Sparkles
} from 'lucide-react';

export default function VideoStudio() {
  const [prompt, setPrompt] = useState('');
  const [duration, setDuration] = useState(6);
  const [aspectRatio, setAspectRatio] = useState('16:9');
  const [generating, setGenerating] = useState(false);
  const [progress, setProgress] = useState(0);
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [statusMessage, setStatusMessage] = useState('');
  const videoRef = useRef<HTMLVideoElement>(null);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;

    setGenerating(true);
    setProgress(0);
    setError(null);
    setVideoUrl(null);
    setStatusMessage('Starting video generation...');

    try {
      // Start generation
      const result = await api.generateVideo(prompt, duration, aspectRatio);

      if (!result.success) {
        throw new Error(result.error || 'Failed to start generation');
      }

      const operationId = result.operationId;
      setStatusMessage('Video is being generated by Veo 3.1...');

      // Poll for status
      let attempts = 0;
      const maxAttempts = 120; // 2 minutes max

      while (attempts < maxAttempts) {
        await new Promise(r => setTimeout(r, 3000)); // Wait 3 seconds

        const status = await api.checkVideoStatus(operationId);

        if (status.status === 'complete' && status.videoUrl) {
          setVideoUrl(status.videoUrl);
          setStatusMessage('Video generated successfully!');
          setProgress(100);
          break;
        } else if (status.status === 'failed' || status.error) {
          throw new Error(status.error || 'Video generation failed');
        } else {
          // Still processing
          const progressPct = Math.min(95, (attempts / maxAttempts) * 100);
          setProgress(progressPct);
          setStatusMessage(`Generating video... ${Math.round(progressPct)}%`);
        }

        attempts++;
      }

      if (attempts >= maxAttempts) {
        throw new Error('Video generation timed out');
      }

    } catch (err: any) {
      setError(err.message || 'Something went wrong');
    } finally {
      setGenerating(false);
    }
  };

  const handleDownload = () => {
    if (!videoUrl) return;

    const link = document.createElement('a');
    link.href = videoUrl;
    link.download = `nexus-video-${Date.now()}.mp4`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const promptSuggestions = [
    "A futuristic city at sunset with flying cars",
    "Ocean waves crashing on a tropical beach",
    "A cozy coffee shop with rain outside",
    "Northern lights dancing over snowy mountains"
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900">
      {/* Header */}
      <header className="border-b border-gray-700/50 bg-gray-900/50 backdrop-blur-sm">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link href="/" className="text-gray-400 hover:text-white transition-colors">
              <ChevronLeft className="w-5 h-5" />
            </Link>
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500 to-pink-600 flex items-center justify-center">
                <Video className="w-5 h-5 text-white" />
              </div>
              <div>
                <h1 className="text-xl font-bold text-white">Video Studio</h1>
                <p className="text-xs text-gray-500">Powered by Veo 3.1 with Audio</p>
              </div>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-6 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Left: Controls */}
          <div className="space-y-6">
            {/* Prompt Input */}
            <div className="bg-gray-800/50 rounded-2xl p-6 border border-gray-700/50">
              <label className="block text-sm font-medium text-gray-300 mb-3">
                Describe your video
              </label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="A cinematic shot of a wolf running through a misty forest at dawn, golden light filtering through the trees..."
                className="w-full h-32 bg-gray-900/50 border border-gray-600 rounded-xl px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent resize-none"
                disabled={generating}
              />

              {/* Suggestions */}
              <div className="mt-3">
                <p className="text-xs text-gray-500 mb-2">Try these:</p>
                <div className="flex flex-wrap gap-2">
                  {promptSuggestions.map((suggestion, i) => (
                    <button
                      key={i}
                      onClick={() => setPrompt(suggestion)}
                      className="text-xs px-3 py-1.5 bg-gray-700/50 hover:bg-gray-700 text-gray-300 rounded-full transition-colors"
                      disabled={generating}
                    >
                      {suggestion.substring(0, 30)}...
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* Settings */}
            <div className="bg-gray-800/50 rounded-2xl p-6 border border-gray-700/50">
              <h3 className="text-sm font-medium text-gray-300 mb-4">Settings</h3>

              <div className="grid grid-cols-2 gap-4">
                {/* Duration */}
                <div>
                  <label className="block text-xs text-gray-500 mb-2 flex items-center gap-1">
                    <Clock className="w-3 h-3" /> Duration
                  </label>
                  <div className="flex gap-2">
                    {[4, 6, 8].map((d) => (
                      <button
                        key={d}
                        onClick={() => setDuration(d)}
                        className={`flex-1 py-2 rounded-lg text-sm font-medium transition-colors ${
                          duration === d
                            ? 'bg-purple-600 text-white'
                            : 'bg-gray-700/50 text-gray-400 hover:bg-gray-700'
                        }`}
                        disabled={generating}
                      >
                        {d}s
                      </button>
                    ))}
                  </div>
                </div>

                {/* Aspect Ratio */}
                <div>
                  <label className="block text-xs text-gray-500 mb-2">Aspect Ratio</label>
                  <div className="flex gap-2">
                    <button
                      onClick={() => setAspectRatio('16:9')}
                      className={`flex-1 py-2 rounded-lg text-sm font-medium transition-colors flex items-center justify-center gap-1 ${
                        aspectRatio === '16:9'
                          ? 'bg-purple-600 text-white'
                          : 'bg-gray-700/50 text-gray-400 hover:bg-gray-700'
                      }`}
                      disabled={generating}
                    >
                      <Monitor className="w-3 h-3" /> 16:9
                    </button>
                    <button
                      onClick={() => setAspectRatio('9:16')}
                      className={`flex-1 py-2 rounded-lg text-sm font-medium transition-colors flex items-center justify-center gap-1 ${
                        aspectRatio === '9:16'
                          ? 'bg-purple-600 text-white'
                          : 'bg-gray-700/50 text-gray-400 hover:bg-gray-700'
                      }`}
                      disabled={generating}
                    >
                      <Smartphone className="w-3 h-3" /> 9:16
                    </button>
                  </div>
                </div>
              </div>
            </div>

            {/* Generate Button */}
            <button
              onClick={handleGenerate}
              disabled={generating || !prompt.trim()}
              className={`w-full py-4 rounded-xl font-semibold text-lg transition-all flex items-center justify-center gap-2 ${
                generating || !prompt.trim()
                  ? 'bg-gray-700 text-gray-500 cursor-not-allowed'
                  : 'bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 text-white shadow-lg shadow-purple-500/25'
              }`}
            >
              {generating ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
                  Generate Video
                </>
              )}
            </button>

            {/* Progress */}
            {generating && (
              <div className="bg-gray-800/50 rounded-xl p-4 border border-gray-700/50">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm text-gray-400">{statusMessage}</span>
                  <span className="text-sm font-medium text-purple-400">{Math.round(progress)}%</span>
                </div>
                <div className="h-2 bg-gray-700 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-gradient-to-r from-purple-500 to-pink-500 transition-all duration-500"
                    style={{ width: `${progress}%` }}
                  />
                </div>
              </div>
            )}

            {/* Error */}
            {error && (
              <div className="bg-red-500/10 border border-red-500/30 rounded-xl p-4">
                <p className="text-red-400 text-sm">{error}</p>
              </div>
            )}
          </div>

          {/* Right: Preview */}
          <div className="bg-gray-800/50 rounded-2xl p-6 border border-gray-700/50">
            <h3 className="text-sm font-medium text-gray-300 mb-4">Preview</h3>

            <div className={`relative rounded-xl overflow-hidden bg-gray-900 ${
              aspectRatio === '9:16' ? 'aspect-[9/16] max-w-[300px] mx-auto' : 'aspect-video'
            }`}>
              {videoUrl ? (
                <video
                  ref={videoRef}
                  src={videoUrl}
                  controls
                  autoPlay
                  loop
                  className="w-full h-full object-contain"
                />
              ) : (
                <div className="absolute inset-0 flex items-center justify-center">
                  {generating ? (
                    <div className="text-center">
                      <Loader2 className="w-12 h-12 text-purple-500 animate-spin mx-auto mb-3" />
                      <p className="text-gray-500 text-sm">Creating your video...</p>
                    </div>
                  ) : (
                    <div className="text-center">
                      <Video className="w-12 h-12 text-gray-600 mx-auto mb-3" />
                      <p className="text-gray-500 text-sm">Your video will appear here</p>
                    </div>
                  )}
                </div>
              )}
            </div>

            {/* Actions */}
            {videoUrl && (
              <div className="flex gap-3 mt-4">
                <button
                  onClick={handleDownload}
                  className="flex-1 py-3 bg-purple-600 hover:bg-purple-500 text-white rounded-xl font-medium transition-colors flex items-center justify-center gap-2"
                >
                  <Download className="w-4 h-4" />
                  Download
                </button>
                <button
                  onClick={() => {
                    setVideoUrl(null);
                    setProgress(0);
                  }}
                  className="py-3 px-4 bg-gray-700 hover:bg-gray-600 text-white rounded-xl font-medium transition-colors flex items-center justify-center gap-2"
                >
                  <RefreshCw className="w-4 h-4" />
                  New
                </button>
              </div>
            )}

            {/* Info */}
            <div className="mt-6 p-4 bg-gray-900/50 rounded-xl">
              <h4 className="text-xs font-medium text-gray-400 mb-2">About Veo 3.1</h4>
              <ul className="text-xs text-gray-500 space-y-1">
                <li>Native audio generation (sound effects, dialogue)</li>
                <li>1080p HD quality, upscale to 4K</li>
                <li>4, 6, or 8 second clips</li>
                <li>~$0.40 per second of video</li>
              </ul>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
